###############################################################
# docker-compose.yml
#
# @author Emmanuel Taylor
#
# @description
#   Creates the Docker network for Swift Recipe. As of now, it 
#   creates and runs containers for both the main SpringBoot
#   application and Cypress.
###############################################################

services:
  swift-recipe:
    image: swift-recipe
    container_name: swift-recipe
    ports:
      - "8080:8080"
    environment:
      - DESCRIPTION_FILE_PATH=classes/static/data/descriptions.txt
      - INGREDIENTS_FILE_PATH=classes/static/data/ingredients.txt
      - INSTRUCTIONS_FILE_PATH=classes/static/data/instructions.txt
    depends_on:
      - mysql

  cypress:
    image: cypress
    container_name: cypress
    environment:
      - CYPRESS_URL=http://swift-recipe:8080/login
    depends_on:
      - swift-recipe
    entrypoint: ["/bin/sh", "-c", "while true; do sleep 30; done"] # Keep container alive.

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=swift-recipe
      - MYSQL_USER=swift-recipe-user
      - MYSQL_PASSWORD=swift-recipe-password
      - MYSQL_ROOT_PASSWORD=root-password